mvsec_root: "data/mvsec/indoor_flying"

splits:
  train:
    - "indoor_flying1"
    - "indoor_flying3"
    - "indoor_flying4"
  test:
    - "indoor_flying2"

camera:
  mode: "right"    # 'left', 'right', or 'random'

event_window: 0.4   # seconds of events before flow timestamp
event_count: 99999999   # num of events per graph (or None)

graph:
  radius: 5
  norm_t: 260
  filtering: true
  delta_t: 5

dataloader:
  batch_size: 1
  num_workers: 1
  shuffle: true
  pin_memory: true
